# Generated by Django 4.0.3 on 2022-04-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='countOfQuestions',
        ),
        migrations.AddField(
            model_name='session',
            name='PH_1',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='session',
            name='PH_2',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='session',
            name='PH_3',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='session',
            name='PH_4',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='session',
            name='countOfAnsweredLevelQuestions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='countOfQuestions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='currentLevel',
            field=models.IntegerField(default=2),
        ),
    ]
