# Generated by Django 4.0.3 on 2022-05-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_session_answered_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='countOfDowngradeLevel',
            field=models.IntegerField(default=0),
        ),
    ]
