# Generated by Django 4.0.3 on 2022-05-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_session_countofdowngradelevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='limit_time',
        ),
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
    ]
