# Generated by Django 4.0.3 on 2022-05-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_remove_question_limit_time_remove_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='countOfQuestions',
        ),
        migrations.RemoveField(
            model_name='session',
            name='countOfTrue',
        ),
        migrations.RemoveField(
            model_name='session',
            name='probability',
        ),
    ]
